[style.description]
underline = false
bold = false
italic = false

[style.command_name]
foreground = "red"
underline = false
bold = false
italic = false

[style.example_text]
foreground = "yellow"
underline = false
bold = false
italic = false

[style.example_code]
foreground = "red"
underline = false
bold = false
italic = false

[style.example_variable]
foreground = "blue"
underline = false
bold = false
italic = false

[display]
compact = true
use_pager = false

[updates]
auto_update = true
auto_update_interval_hours = 360

[directories]
